img_width = 40
img_height = 40
bullet_width = 5
bullet_height = 5
tank_img = 'tank.png'
birth_img = 'birth.png'
boom_img = 'boom.png'
brickwall_img = 'brickwall.png'
steelwall_img = 'steelwall.png'
boss_img= 'boss.png'