from point import Point

img_width = 40
img_height = 40
windows_width = 1000
windows_height = 600
area_width = 900
area_height = 600
bullet_width = 5
bullet_height = 5
default_point = (370, 560)
ai_number = 20
start_music = 'music\\start.ogg'
shoot_music = 'music\\shoot.wav'
tank_img = 'img\\tank.png'
ai_tank_img = 'img\\ai_tank.png'
ai_boss_img = 'img\\ai_boss.png'
gift_tank_img = 'img\\gift_tank.png'
shoot_img = 'img\\shoot.png'
clock_img = 'img\\clock.png'
one_life_img = 'img\\one_life.png'
birth_img = 'img\\birth.png'
boom_img = 'img\\boom.png'
brickwall_img = 'img\\brickwall.png'
steelwall_img = 'img\\steelwall.png'
boss_img= 'img\\boss.png'
background = 'img\\bg.png'
ai_tank_tag = 'img\\ai_tank_tag.png'
player_img = 'img\\player.png'
number_img = 'img\\number.png'
start_img = 'img\\start.png'
gameover_img = 'img\\gameover.png'